#ifndef PREPROCESSING_GLOBAL_H
#define PREPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PREPROCESSING_LIBRARY)
#  define PREPROCESSINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PREPROCESSINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PREPROCESSING_GLOBAL_H
